
env_files = [
  "./.env"
]

[env]
APP_EXTRA_PACAKGES = "com.typesafe:config:1.4.2"
APP_POD_MARKET = "regime-market"
SPARK_CORES_MAX = "1"
SPARK_DRIVER_CORES = "4"
SPARK_DRIVER_MEMORY = "20g"
SPARK_EXECUTOR_CORES = "1"
SPARK_EXECUTOR_MEMORY = "20g"

# cargo make --makefile spark.toml check-vars
[tasks.check-vars]
script = '''
echo K8S_ADDR: ${K8S_ADDR}
echo K8S_NAMESPACE: ${K8S_NAMESPACE}
echo SPARK_ADDR: ${SPARK_ADDR}
'''

# cargo make --makefile spark.toml cluster-info
[tasks.cluster-info]
command = "kubectl"
args = ["cluster-info"]

# cargo make --makefile spark.toml sbt-package
[tasks.sbt-package]
script = [
  "cd ../regime",
  "sbt package"
]

# cargo make --makefile spark.toml send-app
[tasks.send-app]
command = "scp"
args = [
  "-rp",
  "${PROJECT_APP}",
  "${SPARK_APP_DIR}"
]
dependencies = ["sbt-package"]

# cargo make --makefile spark.toml send-conf
[tasks.send-conf]
command = "scp"
args = [
  "-rp",
  "${PROJECT_CONF_DIR}",
  "${SPARK_APP_DIR}/${SPARK_CONF_DIR}",
]

# cargo make --makefile spark.toml send-deps
[tasks.send-deps]
command = "scp"
args = [
  "-rp",
  "${PROJECT_DEPS_DIR}",
  "${SPARK_APP_DIR}"
]

# cargo make --makefile spark.toml exec-task Information AIndexInformation SyncAll
[tasks.exec-task]
script = '''
kubectl run \
  --namespace ${K8S_NAMESPACE} ${APP_POD_MARKET} \
  --rm \
  --tty -i \
  --restart Never \
  --image ${K8S_SPARK_CONTAINER_IMAGE} \
  -- \
  spark-submit \
  --master ${SPARK_ADDR} \
  --deploy-mode cluster \
  --packages ${APP_EXTRA_PACAKGES} \
  --jars ${SPARK_JARS_MSSQL},${SPARK_JARS_MYSQL},${SPARK_JARS_POSTGRES} \
  --class regime.Main \
  ${SPARK_APP} ${@}
'''

# cargo make --makefile spark.toml exec-task Information AIndexInformation SyncAll
[tasks.exec-task-0]
script = '''
kubectl run \
  --namespace ${K8S_NAMESPACE} ${APP_POD_MARKET} \
  --rm \
  --tty -i \
  --restart Never \
  --image ${K8S_SPARK_CONTAINER_IMAGE} \
  -- \
  spark-submit \
  --master ${SPARK_ADDR} \
  --deploy-mode cluster \
  --conf spark.cores.max=${SPARK_CORES_MAX} \
  --conf spark.driver.cores=${SPARK_DRIVER_CORES} \
  --conf spark.driver.memory=${SPARK_DRIVER_MEMORY} \
  --conf spark.executor.cores=${SPARK_EXECUTOR_CORES} \
  --conf spark.executor.memory=${SPARK_EXECUTOR_MEMORY} \
  --packages ${APP_EXTRA_PACAKGES} \
  --jars ${SPARK_JARS_MSSQL},${SPARK_JARS_MYSQL},${SPARK_JARS_POSTGRES} \
  --class regime.Main \
  ${SPARK_APP} ${@}
'''
